/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fshrimp.java.problems;

import fshrimp.java.problems.chap1.Problem8;

public class App {
  public static void main(String[] args) {

    System.out.println(Problem8.removeEmptySpace(" aa bb  cc   d d e e  "));
  }
}
