/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fshrimp.java.problems;

import fshrimp.java.problems.chap1.Problem9;

public class App {
  public static void main(String[] args) {

    String[] strs = {"aa", "bb", "cc"};

    System.out.println(Problem9.mergeStringBySeparator(strs, "+"));
  }
}
